Update bin/test-charm script.

diff --git a/bin/test-charm b/bin/test-charm
--- a/bin/test-charm
+++ b/bin/test-charm
@@ -26,35 +26,59 @@
 # If FAIL_FAST is set to 1 in the environment the testing loop
 # will exit when the first tested browser returns a failure
 # rather than trying them all.
-python lib/deploy_charm_for_testing.py "$@"
-if [ $? -ne 0 ]; then
-    echo "Unable to deploy Charm"
-    exit 1
-fi
 
-# Figure out the URL of the APP.
-export APP_URL=http://`juju status -e juju-gui-testing | grep public-address: | cut -d: -f2 | cut -c2-`
-echo "APP_URL=" ${APP_URL}
-# EXIT_CODE is used to keep track of test failures. If a test fails, this
-# script will exit with an error code.
-EXIT_CODE=0
-# Run the browser tests against the app.
-for JUJU_GUI_TEST_BROWSER in ${JUJU_GUI_TEST_BROWSERS:-ie firefox chrome}
-do
-    export JUJU_GUI_TEST_BROWSER
-    echo Launching ${JUJU_GUI_TEST_BROWSER} tests.
-    python test/test_charm_running.py -v || EXIT_CODE=1
-    if [ ${FAIL_FAST:-0} -eq 1 -a ${EXIT_CODE} -eq 1 ]; then
-        exit 1;
+ENV='juju-gui-testing'
+
+bootstrap_and_deploy() {
+    # Bootstrap a juju enviroment and deploy the Juju GUI charm.
+    python lib/deploy_charm_for_testing.py "$@"
+    retcode=$?
+    if [ $retcode -ne 0 ]; then
+        echo "Unable to deploy Charm"
+        exit $retcode
     fi
-done
-# Destroy the environment, releasing the resources.
-yes | juju destroy-environment -e juju-gui-testing
+}
 
-# Cleanup old internal IP address file if
-# one was created (in deploy for testing).
-if [ -e juju-internal-ip ]; then
-    rm -f juju-internal-ip
-fi
+get_app_url() {
+    # Return the URL of the deployed Juju GUI application.
+    addr=`juju status -e $ENV | grep public-address: | cut -d: -f2 | cut -c2-`
+    echo "http://$addr"
+}
 
-exit $EXIT_CODE
+run_tests() {
+    # Run the CI tests.
+    # retcode is used to keep track of test failures. If a test fails, this
+    # function will exit with an error code.
+    retcode=0
+    # Run the browser tests against the app.
+    for JUJU_GUI_TEST_BROWSER in ${JUJU_GUI_TEST_BROWSERS:-ie firefox chrome}
+    do
+        export JUJU_GUI_TEST_BROWSER
+        echo "Launching $JUJU_GUI_TEST_BROWSER tests."
+        python test/test_charm_running.py -v || retcode=1
+        if [ ${FAIL_FAST:-0} -eq 1 -a $retcode -eq 1 ]; then
+            exit 1;
+        fi
+    done
+    return retcode
+}
+
+on_exit() {
+    # Destroy the environment, releasing the resources.
+    echo "Quitting..."
+    #yes | juju destroy-environment -e $ENV
+    # Cleanup old internal IP address file if
+    # one was created (in deploy for testing).
+    if [ -e juju-internal-ip ]; then
+        rm -f juju-internal-ip
+    fi
+}
+
+# Ensure we clean up things even if this script exits with an error.
+trap on_exit EXIT
+
+# Launch the script.
+bootstrap_and_deploy $@
+export APP_URL=`get_app_url`
+echo "APP_URL = $APP_URL"
+exit `run_tests`
