bail on failed deploy

diff --git a/bin/test-charm b/bin/test-charm
--- a/bin/test-charm
+++ b/bin/test-charm
@@ -4,6 +4,11 @@
 # sudo apt-get install python-shelltoolbox python-selenium python-yaml juju
 # Deploy the charm, using a branch if given.
 python lib/deploy_charm_for_testing.py "$@"
+if [ $? -ne 0 ]; then
+    echo "Unable to deploy Charm"
+    exit 1
+fi
+
 # Figure out the URL of the APP.
 export APP_URL=http://`juju status -e juju-gui-testing | grep public-address: | cut -d: -f2 | cut -c2-`
 # EXIT_CODE is used to keep track of test failures. If a test fails, this
